### ISSUE TITLE
Cannot statically evaluate fs argument

### ISSUE THREAD

**Issue by blksmr** [flowforfrank/react-electron-parcel-boilerplate#1]
anyway to include
`const remote = require("electron").remote;` inside the index.js ?
cuz i'm getting stuck at Cannot statically evaluate fs argument error fs.existsSync is not a function
help ?

**Comment by flowforfrank** [comment]
Hi @asmirbelkic 

I've pushed in a fix, please see [643d8c4](https://github.com/flowforfrank/react-electron-parcel-boilerplate/commit/643d8c4b85caa88b443ed5b24d8d91c87bfb5382) for the changes.

Now you should be able to do

```javascript
import { remote } from "electron"
```

Please note that the remote module is [disabled by default](https://www.electronjs.org/docs/breaking-changes#default-changed-enableremotemodule-defaults-to-false) for the latest version of Electron, so you need to enable it using the following flag in `dev.js`

```diff
const window = new BrowserWindow({
    webPreferences: {
        nodeIntegration: true,
+      enableRemoteModule: true
    }
});
```

Otherwise, after importing `remote`, it will have a value of `undefined`. Also, it is recommended to use the [ipcRenderer](https://www.electronjs.org/docs/api/ipc-renderer) instead. You can have a further read here on why `remote` is condifered harmful:

[Medium - Electron’s ‘remote’ module considered harmful](https://nornagon.medium.com/electrons-remote-module-considered-harmful-70d69500f31)

Let me know if you still experience any problem.

**Comment by asmirbelkic** [comment]
That's nice, i actually do not use react with your boilerplate i had to edit it a bit it's fully working, one of the interesting thing is that devtools console log is not recognising any variable from components when i add remote and if i try to console log it inside the webtools it's that the variable is not defined what is this come from ?


Ty again ur boilerplate is kinda amazing.

**Comment by blksmr** [comment]
Very cool thank's i tried and it works good, my last problem is that i cannot get console.log(remote)
I am able to get console log or remote if it's in the source code but can't inside the devtool :/
keeps saying `ReferenceError: remote is not defined`

Thank you again for your help ! :)
is this maybe because of parcel ? maybe variable arn't accessible cuz they are encapsulated ?

**Comment by flowforfrank** [comment]
Could you please provide reproduction steps? I'm able to get `remote` logged to the console.

**Comment by blksmr** [comment]
Oh that's strange, but yeah,
```
import { remote } from "electron";
const win = remote.getCurrentWindow();
```

Run the app as dev, open devtools inside the app and type in console.log(win) or remote.
Btw remote and win are inside a component

**Comment by flowforfrank** [comment]
You cannot `console.log` variables from DevTools, those are scoped to the modules. You need to include the `console.log` after the variable declaration or use the `debugger` keyword to debug your app:

```javascript
import { remote } from 'electron'

const win = remote.getCurrentWindow();

// Use `console.log` inside your code
console.log(win);

// Use the debugger keyword to stop code execution at the specified line
debugger;
```
